# Generated by Django 4.1.3 on 2023-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='Status',
            field=models.CharField(default='In-Progress', max_length=30),
        ),
    ]
