# Generated by Django 4.1.3 on 2023-06-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_progress_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='categories',
            new_name='category',
        ),
    ]
