# Generated by Django 4.1.3 on 2023-07-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_rename_country_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
