# Generated by Django 4.1.3 on 2023-07-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_progress_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='percentage',
            field=models.IntegerField(default=1),
        ),
    ]
